[package]
name = "hnefatafl"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
rand = "0.10.2"

# Make release as small as possible
[profile.release]
strip = true      # Automatically strip symbols from the binary.
opt-level = "z"   # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"

[profile.release-wasm]
inherits = "release"
strip = false        # Don't strip — wasm doesn't need this
opt-level = "z"
lto = false          # Must be off for macroquad wasm
codegen-units = 1
panic = "abort"      # wasm32 already defaults to this, but fine to keep
